SELECT A.ANIMAL_ID, A.ANIMAL_TYPE, A.NAME
FROM ANIMAL_INS AS A
JOIN ANIMAL_OUTS AS B
ON A.ANIMAL_ID=B.ANIMAL_ID
WHERE A.SEX_UPON_INTAKE LIKE 'INTACT%' AND (B.SEX_UPON_OUTCOME LIKE 'SPAYED%' OR B.SEX_UPON_OUTCOME LIKE 'NEUTERED%')
ORDER BY A.ANIMAL_ID ASC;

# 오답 이유: LIKE와 =의 차이
# =은 완벽히 동일, 하나와 하나를 비교하지만, LIKE는 조건에 맞게 더 유연하며 두개 이상을 찾을 때 사용