SELECT A.NAME, A.DATETIME
FROM ANIMAL_INS AS A
WHERE
NOT EXISTS (
    # A에 B동물이 없는지
    SELECT *
    FROM ANIMAL_OUTS AS B
    WHERE A.ANIMAL_ID=B.ANIMAL_ID
)
ORDER BY A.DATETIME ASC
LIMIT 3; # 출력 제한 3 (가장 먼저 들어온 3마리)