-- 조건에 맞는 사원 정보 조회하기
WITH GROUP_EMP AS (
    SELECT SUM(G.SCORE) AS SCORE, E.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL 
    FROM HR_EMPLOYEES AS E
    JOIN HR_GRADE AS G
    ON E.EMP_NO = G.EMP_NO
    WHERE G.YEAR = '2022'
    GROUP BY E.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
)

SELECT SCORE, EMP_NO, EMP_NAME, POSITION, EMAIL
FROM GROUP_EMP
WHERE SCORE = (SELECT MAX(SCORE) FROM GROUP_EMP);
