SELECT USER_ID, PRODUCT_ID
FROM ONLINE_SALE
GROUP BY USER_ID, PRODUCT_ID
HAVING COUNT(PRODUCT_ID) >= 2
ORDER BY USER_ID ASC, PRODUCT_ID DESC;

# 동일 회원이 동일한 상품을 재구매한 데이터 조회해야 하므로
# GROUP BY 절: USER_ID와 PRODUCT_ID 를 그룹화
# HAVING 절: 그룹화 조건으로 PRODUCT_ID의 개수가 2 이상인 것만 그룹화