SELECT PT_NAME, PT_NO, GEND_CD, AGE, IFNULL(TLNO, 'NONE') AS TLNO
FROM PATIENT
WHERE PATIENT.GEND_CD='W' AND PATIENT.AGE<=12
ORDER BY AGE DESC, PT_NAME ASC;

# IFNULL(칼럼명, '대체할 값') 메서드: 해당 칼럼에 NULL인 데이터가 있으면 '데체할 값'으로 데체한다는 메서드