SELECT A.FLAVOR
FROM FIRST_HALF AS A
JOIN (SELECT FLAVOR, SUM(TOTAL_ORDER) AS JULY_TOTAL
     FROM JULY
     GROUP BY FLAVOR) AS B
ON A.FLAVOR = B.FLAVOR
ORDER BY A.TOTAL_ORDER + B.JULY_TOTAL DESC
LIMIT 3;