SELECT A.ID, A.EMAIL, A.FIRST_NAME, A.LAST_NAME
FROM DEVELOPERS AS A
WHERE A.SKILL_CODE & (SELECT CODE
                     FROM SKILLCODES
                     WHERE NAME = 'Python') > 0
OR  A.SKILL_CODE & (SELECT CODE
                   FROM SKILLCODES
                   WHERE NAME = 'C#') > 0
ORDER BY A.ID ASC;